=== valkolovos/mdf/src/main/resources/MockTestData.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<xsd:schema xmlns="http://www.orbitz.com/schema/mock-data" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.orbitz.com/schema/mock-data">

  <xsd:element name="mock-data">
    <xsd:annotation>
      <xsd:documentation>The top level element.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
          <xsd:element ref="description" minOccurs="0" maxOccurs="1" />
          <xsd:element ref="categoryMatcher" minOccurs="0" maxOccurs="1" />
          <xsd:element ref="parameterMatcher" minOccurs="0" maxOccurs="1" />
          <xsd:element ref="parameterMorpher" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="import" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="variable" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="template" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="category" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="import">
    <xsd:complexType>
        <xsd:attribute name="file" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="category">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="variable" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="template" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="test" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="test">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="request" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="response" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="request">
    <xsd:complexType>
      <xsd:sequence>
      	<xsd:element ref="use-template" maxOccurs="unbounded" minOccurs="0"/>
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="response">
    <xsd:complexType>
        <xsd:sequence>
        	<xsd:element ref="use-template" maxOccurs="unbounded" minOccurs="0" />
            <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="delay" type="xsd:long"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="param">
    <xsd:complexType>
      <xsd:sequence>
      	<xsd:element ref="use-template" maxOccurs="unbounded" minOccurs="0"/>
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="optional" type="xsd:string"/>
      <xsd:attribute name="type" use="optional" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="description" type="xsd:string"/>
  <xsd:element name="template">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="description" minOccurs="0"/>
        <xsd:element ref="use-template" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name" use="required">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:pattern value="[a-zA-Z0-9_-]+"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="use-template">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name" use="required">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:pattern value="[a-zA-Z0-9_-]+"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="append-params" type="xsd:boolean" use="optional" default="true"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="variable">
    <xsd:complexType>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:simpleType name="class">
      <xsd:restriction base="xsd:string">
        <xsd:pattern value="[a-zA-Z0-9_.]+"/>
      </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="id">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[a-zA-Z0-9_-]+"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:attributeGroup name="matcherAttributes">
      <xsd:attribute name="id" use="optional" type="id"/>
      <xsd:attribute name="class" use="required" type="class"/>
  </xsd:attributeGroup>
  
  <xsd:attributeGroup name="morpherAttributes" >
      <xsd:attribute name="id" use="optional" type="id"/>
      <xsd:attribute name="class" use="optional" type="class"/>
      <xsd:attribute name="ref" use="optional" type="id"/>
  </xsd:attributeGroup>
  
  <xsd:element name="categoryMatcher">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="categoryMatcher" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attributeGroup ref="matcherAttributes"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="parameterMatcher">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="parameterMatcher" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attributeGroup ref="matcherAttributes"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="parameterMorpher">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attributeGroup ref="morpherAttributes"/>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== valkolovos/mdf/src/test/resources/org/mdf/mockdata/MockDataAwareConcurrentHashMapTestData.xml
<mock-data xmlns="http://www.orbitz.com/schema/mock-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
          http://www.orbitz.com/schema/mock-data
          ../../../../../main/MockTestData.xsd ">
	<parameterMorpher class="org.mdf.xml.XmlParameterMatcherMorpher" />
	<template name="execute-service-template">
		<param name="serviceInterface" value="com.orbitz.servicetests.ojf.TestService" />
		<param name="methodName" value="executeService" />
		<param name="arg1" value="This is my request." />
		<param name="arg2" value="It has two values." />
	</template>
	<category name="cat">
		<test>
			<request>
				<param name="key">
				<param name="long" value="1" />
				<param name="long" value="2" />
				<param name="Implementation Type" value="java.lang.Long-array" />
				</param>
			</request>
			<response>
			<param name="value">
				<param name="long" value="1" />
				<param name="long" value="2" />
				<param name="long" value="3" />
				<param name="Implementation Type" value="java.lang.Long-array" />
				</param>
			</response>
		</test>
	</category>
</mock-data>

=== valkolovos/mdf/src/test/resources/org/mdf/mockdata/MockDataManagerVariableTestConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<mock-data xmlns="http://www.orbitz.com/schema/mock-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.orbitz.com/schema/mock-data ../../../../../main/MockTestData.xsd ">
    <description>
    This is a test configuration file for the MockDataManager class.
  </description>
    <variable name="global_var1" value="var1" />
    <variable name="overrideable_var" value="overrideable" />
    <template name="template">
        <param name="overrideable variable" value="@overrideable_var" />
    </template>
    <category>
        <description>Basic variable replacement</description>
        <variable name="category_var1" value="cat_var1" />
        <test>
            <request>
                <param name="@global_var1" value="value" />
            </request>
            <response>
                <param name="response" value="@category_var1" />
            </response>
        </test>
        <test>
            <description>Nested param variable replacement test</description>
            <request>
                <param name="parent">
                    <param name="child-param" value="@global_var1" />
                </param>
            </request>
            <response>
                <param name="parent">
                    <param name="@category_var1" value="child-param" />
                </param>
            </response>
        </test>
    </category>
    <category>
        <variable name="overrideable_var" value="cat2_var" />
        <test>
            <description>Test overriding global variables</description>
            <request>
                <param name="@overrideable_var" value="name is overridden" />
            </request>
            <response />
        </test>
        <test>
            <description>Test that override applies in nested params</description>
            <request />
            <response>
                <param name="parent">
                    <param name="child-param" value="@overrideable_var" />
                </param>
            </response>
        </test>
    </category>
    <category>
        <test>
            <request>
                <use-template name="template" />
            </request>
            <response />
        </test>
    </category>
    <category>
        <variable name="overrideable_var" value="templated_var" />
        <variable name="category_var" value="cat_var" />
        <test>
            <request>
                <use-template name="template" />
            </request>
            <response />
        </test>
        <test>
            <description>Test template params with variable names</description>
            <request>
                <use-template name="template">
                    <param name="overrideable variable" value="@category_var" />
                </use-template>
            </request>
            <response>
                <use-template name="template">
                    <param name="parent">
                        <param name="child-param" value="@overrideable_var" />
                    </param>
                </use-template>
            </response>
        </test>
    </category>
    <category>
        <variable name="VarName" value="REPLACED"/>
        <test>
            <request>
                <param name="@VarName@.Extra" value="Foo"/>
                <param name="Foo" value="Prefixed.@VarName@.Value"/>
                <param name="No Variable, No Value"/>
                <param name="PrefixedOnly.@VarName@"/>
            </request>
            <response/>
        </test>
    </category>
    <category>
        <test>
            <request>
                <param name="email" value="test@orbitz.com"/>
                <param name="value_with@symbol" value="exists"/>
            </request>
            <response/>
        </test>
    </category>
</mock-data>

=== valkolovos/mdf/src/test/resources/org/mdf/mockdata/MockDataAwareMapTestData.xml
<?xml version="1.0" encoding="UTF-8"?>
<mock-data xmlns="http://www.orbitz.com/schema/mock-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.orbitz.com/schema/mock-data ../../../../../main/MockTestData.xsd ">
    <category name="map">
        <test>
            <request>
                <param name="key" value="foo"/>
            </request>
            <response>
                <param name="value" value="house">
                    <param name="Implementation Type" value="java.lang.String"/>
                </param>
            </response>
        </test>
        <test>
            <request>
                <param name="key">
                    <param name="__stringField" value="krakatoa"/>
                    <param name="Implementation Type" value="org.mdf.mockdata.ComplexClass2"/>
                </param>
            </request>
            <response>
                <param name="value">
                    <param name="stringField" value="stringField"/>
                    <param name="mapField">
                        <param name="entry">
                            <param name="string" value="key1"/>
                            <param name="org.mdf.mockdata.ComplexClass2">
                                <param name="__stringField" value="value1"/>
                            </param>
                        </param>
                    </param>
                    <param name="longArray">
                        <param name="long" value="1"/>
                        <param name="long" value="2"/>
                        <param name="long" value="3"/>
                    </param>
                    <param name="child">
                        <param name="stringField" value="childStringField"/>
                        <param name="mapField">
                            <param name="entry">
                                <param name="string" value="key1"/>
                                <param name="org.mdf.mockdata.ComplexClass2">
                                    <param name="__stringField" value="value1"/>
                                </param>
                            </param>
                        </param>
                        <param name="longArray">
                            <param name="long" value="1"/>
                            <param name="long" value="2"/>
                            <param name="long" value="3"/>
                        </param>
                        <param name="booleanList">
                            <param name="XStream Attribute: class" value="linked-list"/>
                            <param name="boolean" value="true"/>
                            <param name="boolean" value="false"/>
                        </param>
                    </param>
                    <param name="booleanList">
                        <param name="XStream Attribute: class" value="linked-list"/>
                        <param name="boolean" value="true"/>
                        <param name="boolean" value="false"/>
                    </param>
                    <param name="sameChild">
                        <param name="stringField" value="childStringField"/>
                        <param name="mapField">
                            <param name="entry">
                                <param name="string" value="key1"/>
                                <param name="org.mdf.mockdata.ComplexClass2">
                                    <param name="__stringField" value="value1"/>
                                </param>
                            </param>
                        </param>
                        <param name="longArray">
                            <param name="long" value="1"/>
                            <param name="long" value="2"/>
                            <param name="long" value="3"/>
                        </param>
                        <param name="booleanList">
                            <param name="XStream Attribute: class" value="linked-list"/>
                            <param name="boolean" value="true"/>
                            <param name="boolean" value="false"/>
                        </param>
                    </param>
                    <param name="Implementation Type" value="org.mdf.mockdata.ComplexClass"/>
                </param>
            </response>
        </test>
		<test>
            <request>
                <param name="key">
                    <param name="long" value="1"/>
                    <param name="long" value="2"/>
                    <param name="Implementation Type" value="java.lang.Long-array"/>
                </param>
            </request>
            <response>
                <param name="value">
                    <param name="long" value="3"/>
                    <param name="long" value="4"/>
                    <param name="Implementation Type" value="java.lang.Long-array"/>
                </param>
            </response>
        </test>
    </category>
</mock-data>

=== valkolovos/mdf/src/test/resources/org/mdf/mockdata/MockDataManagerTestConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<mock-data xmlns="http://www.orbitz.com/schema/mock-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.orbitz.com/schema/mock-data ../../../../../main/MockTestData.xsd ">
    <description>
    This is a test configuration file for the MockDataManager class.
  </description>
    <parameterMorpher class="org.mdf.mockdata.GenerateMultiplesMorpher">
        <param name="defaultParameterName" value="morphable_1"/>
    </parameterMorpher>
    <parameterMorpher class="org.mdf.mockdata.IncrementingMorpher">
        <param name="paramName" value="plusDays"/>
        <param name="useValueAsParamName" value="false"/>
    </parameterMorpher>
    <parameterMorpher class="org.mdf.mockdata.VariableParamToDateMorpher">
        <param name="defaultParameterName" value="date_param"/>
    </parameterMorpher>
    <category>
        <description>
      This is description for the category. At runtime, we should ignore this because it's a waste of memory.
      However, it's quite useful to have around for documentation.
    </description>
        <template name="response-template">
            <description>
        This is a sample template
      </description>
            <param name="response_param1" value="default response param1 value" />
            <param name="complex_param">
                <param name="childparam1" value="childparam1 value" />
            </param>
            <param name="complex_param">
                <param name="childparam1" value="childparam1 value" />
            </param>
        </template>
        <template name="child-param-template">
            <description>This is a child param template</description>
            <param name="param 1" value="param 1 value" />
            <param name="param 2" value="param 2 value" />
        </template>
        <template name="ComplexClass2-template">
            <param name="_stringField" value="ComplexClass2 String" />
        </template>
        <template name="ComplexClass-template">
            <param name="stringField" value="ComplexClass String" />
            <param name="mapField">
                <param name="mapEntry" />
            </param>
            <param name="longArray" value="null" />
            <param name="child" />
            <param name="booleanList">
                <param name="iterableEntry" value="false" />
                <param name="iterableEntry" value="true" />
            </param>
            <param name="sameChild" />
            <param name="nullObject" value="null" />
            <param name="_c2">
                <use-template name="ComplexClass2-template">
                    <param name="_stringField" value="_c2 String value" />
                </use-template>
            </param>
        </template>
        <test>
            <request>
                <param name="param1" value="value" />
            </request>
            <response>
                <param name="response_param1" value="response param1 value" />
                <param name="complex_param">
                    <param name="childparam1" value="childparam1 value" />
                </param>
            </response>
        </test>
        <test>
            <request>
                <param name="param2" value="value" />
            </request>
            <response>
                <use-template name="response-template">
                    <param name="complex_param[1].childparam1" value="templated param" />
                    <param name="complex_param[2]">
                        <param name="childparam1" value="overridden child value" />
                    </param>
                    <param name="new_param">
                        <param name="childparam" value="new param - child param" />
                    </param>
                    <param name="templated-param">
                        <use-template name="child-param-template" />
                    </param>
                </use-template>
            </response>
        </test>
        <test>
            <request>
                <param name="param3" value="value" />
            </request>
            <response>
                <param name="templated-param">
                    <use-template name="child-param-template">
                        <param name="param 1" value="replaced param value 1" />
                    </use-template>
                </param>
                <param name="templated-param">
                    <use-template name="child-param-template">
                        <param name="param 2" value="replaced param value 2" />
                    </use-template>
                </param>
            </response>
        </test>
        <test>
            <request>
                <param name="param4" value="value" />
            </request>
            <response>
                <param name="templated-param">
                    <param name="child-param" value="this is a child param" />
                    <param name="child-param-with-children">
                        <use-template name="child-param-template" />
                    </param>
                </param>
            </response>
        </test>
        <test>
            <request>
                <param name="param5" value="value" />
            </request>
            <response>
                <param name="response">
                    <use-template name="ComplexClass-template">
                        <param name="booleanList">
                            <param name="iterableEntry" value="false" />
                            <param name="iterableEntry" value="false" />
                            <param name="iterableEntry" value="false" />
                        </param>
                        <param name="child">
                            <use-template name="ComplexClass-template">
                                <param name="id" value="1" />
                            </use-template>
                        </param>
                        <param name="sameChild">
                            <param name="reference" value="1" />
                        </param>
                    </use-template>
                </param>
            </response>
        </test>
        <test>
            <description>Test Response Delay</description>
            <request>
                <param name="delay_test" value="true" />
            </request>
            <response delay="5000">
                <param name="delay_response" value="5000" />
            </response>
        </test>
    </category>
    <category>
        <test>
            <description>Test nested parameter morphers</description>
            <request>
                <param name="nested_morphers" value="true" />
            </request>
            <response>
                <param name="morphable_1" value="2">
                    <param name="date_param">
                        <param name="plusDays"/>
                        <param name="format" value="yyyy-MM-dd" />
                    </param>
                </param>
            </response>
        </test>
    </category>
</mock-data>
