=== valkolovos/mdf/src/main/resources/MockTestData.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<xsd:schema xmlns="http://www.orbitz.com/schema/mock-data" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.orbitz.com/schema/mock-data">

  <xsd:element name="mock-data">
    <xsd:annotation>
      <xsd:documentation>The top level element.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
          <xsd:element ref="description" minOccurs="0" maxOccurs="1" />
          <xsd:element ref="categoryMatcher" minOccurs="0" maxOccurs="1" />
          <xsd:element ref="parameterMatcher" minOccurs="0" maxOccurs="1" />
          <xsd:element ref="parameterMorpher" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="import" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="variable" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="template" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="category" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="import">
    <xsd:complexType>
        <xsd:attribute name="file" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="category">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="variable" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="template" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="test" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="test">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="request" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="response" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="request">
    <xsd:complexType>
      <xsd:sequence>
      	<xsd:element ref="use-template" maxOccurs="unbounded" minOccurs="0"/>
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="response">
    <xsd:complexType>
        <xsd:sequence>
        	<xsd:element ref="use-template" maxOccurs="unbounded" minOccurs="0" />
            <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="delay" type="xsd:long"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="param">
    <xsd:complexType>
      <xsd:sequence>
      	<xsd:element ref="use-template" maxOccurs="unbounded" minOccurs="0"/>
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="optional" type="xsd:string"/>
      <xsd:attribute name="type" use="optional" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="description" type="xsd:string"/>
  <xsd:element name="template">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="description" minOccurs="0"/>
        <xsd:element ref="use-template" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name" use="required">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:pattern value="[a-zA-Z0-9_-]+"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="use-template">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name" use="required">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:pattern value="[a-zA-Z0-9_-]+"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="append-params" type="xsd:boolean" use="optional" default="true"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="variable">
    <xsd:complexType>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:simpleType name="class">
      <xsd:restriction base="xsd:string">
        <xsd:pattern value="[a-zA-Z0-9_.]+"/>
      </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="id">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[a-zA-Z0-9_-]+"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:attributeGroup name="matcherAttributes">
      <xsd:attribute name="id" use="optional" type="id"/>
      <xsd:attribute name="class" use="required" type="class"/>
  </xsd:attributeGroup>
  
  <xsd:attributeGroup name="morpherAttributes" >
      <xsd:attribute name="id" use="optional" type="id"/>
      <xsd:attribute name="class" use="optional" type="class"/>
      <xsd:attribute name="ref" use="optional" type="id"/>
  </xsd:attributeGroup>
  
  <xsd:element name="categoryMatcher">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="categoryMatcher" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attributeGroup ref="matcherAttributes"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="parameterMatcher">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="parameterMatcher" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attributeGroup ref="matcherAttributes"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="parameterMorpher">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attributeGroup ref="morpherAttributes"/>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== valkolovos/mdf/src/test/resources/org/mdf/mockdata/MockDataManagerExclRulesTemplateTestConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<mock-data xmlns="http://www.orbitz.com/schema/mock-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.orbitz.com/schema/mock-data ../../../../../main/MockTestData.xsd ">
    <template name="exclusion_rule">
        <param name="excl_rule_id" value="" />
        <param name="rule_name" value="Rule" />
        <param name="description" value="Description" />
        <param name="is_active_ind" value="1" />
        <param name="priority" value="1" />
        <param name="rule_data" value="" />
        <param name="username" value="user" />
        <param name="update_reason" value="update reason" />
    </template>
    <template name="excl_data">
        <param name="hotel:condition" />
    </template>
    <template name="trial1_data">
        <param name="trial1" value="hotel:trial1" />
    </template>
    <template name="trial2_data">
        <param name="trial2" value="hotel:trial2" />
    </template>
    <template name="excl_consequence">
        <param name="hotel:consequence">
            <param name="hotel:exclude-rate-host">
                <param name="attributes">
                    <param name="name" value="hotelRateHost" />
                </param>
            </param>
        </param>
    </template>
    <template name="excl_rate_host">
        <param name="hotel:hotel-rate-host">
            <param name="attributes">
                <param name="name" value="hotelRateHost" />
            </param>
            <param name="hotel:host" />
        </param>
    </template>
    <category name="Exclusion Rule Category">
        <param name="sqlSnippet" value="from excl_rule this_ where this_.is_active_ind=?" />
        <test>
            <request>
                <param name="1" value="true" />
            </request>
            <response>
                <param name="row">
                    <use-template name="exclusion_rule">
                        <param name="excl_rule_id" value="" />
                        <param name="description" value="Dust GTA" />
                        <param name="rule_data">
                            <use-template name="excl_data">
                                <param name="hotel:condition">
                                    <use-template name="excl_rate_host">
                                        <param name="hotel:host">
                                            <param name="hotel:equals" value="GTA" />
                                        </param>
                                    </use-template>
                                </param>
                            </use-template>
                            <use-template name="trial1_data">
                                <param name="trial1" value="hotel:trial3" />
                            </use-template>
                            <use-template name="trial2_data">
                                <param name="trial2" value="hotel:trial4" />
                            </use-template>
                        </param>
                    </use-template>
                </param>
            </response>
        </test>
    </category>
</mock-data>

=== valkolovos/mdf/src/test/resources/org/mdf/mockdata/SequenceGeneratingMatcherMorpherTestData.xml
<?xml version="1.0" encoding="UTF-8"?>
<mock-data xmlns="http://www.orbitz.com/schema/mock-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.orbitz.com/schema/mock-data ../../../../../main/MockTestData.xsd ">
  <parameterMatcher id="sequenceMatcherMorpher" class="org.mdf.mockdata.SequenceGeneratingMatcherMorpher">
    <param name="SEQUENCE_NAME.nextval" value="SEQUENCE_NAME"/>
    <param name="SEQUENCE_2.nextval" value="SEQUENCE_2">
    	<param name="init" value="4"/>
    </param>
  </parameterMatcher>
  <parameterMorpher ref="sequenceMatcherMorpher"/>
  <category>
    <test>
      <request>
        <param name="foo" value="bar"/>
      </request>
      <response>
        <param name="SEQUENCE_NAME.nextval"/>
      </response>
    </test>
    <test>
      <request>
        <param name="1" value="SEQUENCE_NAME"/>
      </request>
      <response>
        <param name="response" value="response value"/>
      </response>
    </test>
    <test>
    	<request>
    		<param name="house" value="corn"/>
    	</request>
    	<response>
    		<param name="SEQUENCE_2.nextval"/>
    	</response>
    </test>
  </category>
</mock-data>

=== valkolovos/mdf/src/test/resources/org/mdf/xml/XmlParameterMorpherTestData.xml
<?xml version="1.0" encoding="UTF-8"?>
<mock-data xmlns="http://www.orbitz.com/schema/mock-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.orbitz.com/schema/mock-data ../../../../../main/MockTestData.xsd ">
    <parameterMatcher id="xmlMatcherMorpher" class="org.mdf.xml.XmlParameterMatcherMorpher"/>
    <parameterMorpher ref="xmlMatcherMorpher"/>
    <category>
        <test>
            <request>
                <param name="//EngineDoc/ContentType" value="OrderFormDoc" />
                <param name="//EngineDoc/OrderFormDoc/Consumer/PaymentMech/CreditCard/Number" value="5200000000000007" />
            </request>
            <response>
                <param name="response" />
            </response>
        </test>
        <test>
            <request>
                <param name="/test" value="true" />
            </request>
            <response>
                <param name="xml-response">
                    <param name="DocVersion" value="1.0" />
                    <param name="EngineDoc">
                        <param name="ContentType" value="OrderFormDoc" />
                        <param name="IPAddress" value="127.0.0.1" />
                        <param name="OrderFormDoc">
                            <param name="Mode" value="P" />
                            <param name="Transaction">
                                <param name="AuthCode" value="AuthCode" />
                                <param name="CardProcResp">
                                    <param name="AvsDisplay" value="YY" />
                                    <param name="AvsRespCode" value="YY" />
                                    <param name="CcErrCode" value="1">
                                        <param name="xml attributes">
                                            <param name="DataType" value="S32" />
                                        </param>
                                    </param>
                                    <param name="CcReturnMsg" value="Approved" />
                                    <param name="Cvv2Resp" value="1" />
                                    <param name="ProcReturnCode" value="1" />
                                    <param name="ProcReturnMsg" value="Message" />
                                    <param name="Status" value="Success" />
                                </param>
                                <param name="CurrentTotals">
                                    <param name="Totals">
                                        <param name="Total" value="00">
                                            <param name="xml attributes">
                                                <param name="DataType" value="Money" />
                                                <param name="Currency" value="840" />
                                            </param>
                                        </param>
                                    </param>
                                </param>
                                <param name="Id" value="TxId123" />
                                <param name="Type" value="PreAuth" />
                            </param>
                        </param>
                    </param>
                </param>
            </response>
        </test>
    </category>
</mock-data>

=== valkolovos/mdf/src/test/resources/org/mdf/mockdata/MockCallableStatementTestData.xml
<?xml version="1.0" encoding="UTF-8"?>
<mock-data xmlns="http://www.orbitz.com/schema/mock-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.orbitz.com/schema/mock-data ../../../../../main/MockTestData.xsd ">
    <parameterMorpher class="org.mdf.mockdata.SequenceGeneratingMatcherMorpher">
        <param name="SEQUENCE_NAME_PARAM" value="SEQUENCE_NAME"/>
    </parameterMorpher>
    <category name="basicOutParameterStatement">
        <param name="sqlSnippet" value="call insert into dps.package_remark" />
        <test>
            <request/>
            <response>
                <param name="SEQUENCE_NAME_PARAM" value="5"/>
            </response>
        </test>
    </category>
</mock-data>

=== valkolovos/mdf/src/test/resources/org/mdf/mockdata/MockAdvancedTemplateConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<mock-data xmlns="http://www.orbitz.com/schema/mock-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.orbitz.com/schema/mock-data ../../../../../main/MockTestData.xsd ">
    <description>
    This is a test configuration file for the MockDataManager class.
  </description>
    <category>
        <template name="search_template">
            <param name="id" value="1" />

            <param name="code" value="TC" />
            <param name="name" value="Orbitz Hotel" />
            <param name="latitude" value="41.8819" />

            <param name="longitude" value="-87.6397" />
            <param name="postalcode" value="60061" />
            <param name="city" value="Chicago" />
            <param name="address1" value="500 W Madison ST" />
            <param name="address2" value="" />
            <param name="state" value="IL" />
            <param name="country" value="US" />
            <param name="pos" value="ORB" />
        </template>
        <template name="nested_params">
            <param name="level1">
                <param name="first" value="1" />
                <param name="first.second" value="2">
                    <param name="third" value="3" />
                </param>
                <param name="first.second">
                    <param name="fourth" value="4" />
                </param>
            </param>
        </template>

        <template name="generic_template">
            <param name="exist" value="" />
        </template>

        <template name="2_deep_inherited_template">
            <param name="existing" value="old_one" />
            <param name="existing" value="old_two" />
        </template>

        <template name="inherited_template">
            <use-template name="2_deep_inherited_template">
                <param name="existing[1]" value="replaced" />
                <param name="new" value="new" />
            </use-template>
            <use-template name="2_deep_inherited_template" />

            <param name="inherited_param"></param>
        </template>

        <template name="top_template">
            <use-template name="inherited_template" />
            <param name="top_param" />
        </template>

        <template name="common-template">
            <param name="common-a">
                <param name="a" value="1"/>
            </param>
            <param name="common-b" value="2"/>
        </template>
        <template name="parent-template">
            <param name="object">
                <param name="field" value="this is a field"/>
                <param name="common_field">
                    <use-template name="common-template"/>
                </param>
            </param>
        </template>
        <template name="child-a">
            <use-template name="parent-template">
                <param name="object.field" value="this is another field"/>
                <param name="object.common_field">
                    <use-template name="common-template">
                        <param name="common-a.a" value="2"/>
                    </use-template>
                </param>
            </use-template>
        </template>
        <template name="child-b">
            <use-template name="parent-template">
                <param name="object.common_field">
                    <use-template name="common-template">
                        <param name="common-a.a" value="3"/>
                    </use-template>
                </param>
            </use-template>
        </template>

        <test>
            <request>
                <param name="param1" value="value" />
            </request>
            <response>
                <param name="response">
                    <use-template name="search_template">
                        <param name="name" value="E-Bookers Hotel">
                            <param name="level2">
                                <param name="level3">
                                    <use-template name="generic_template">
                                        <param name="foo" />
                                    </use-template>
                                </param>
                            </param>
                        </param>
                    </use-template>
                </param>
            </response>
        </test>
        <test>
            <request>
                <param name="param2" value="value" />
            </request>
            <response>
                <use-template name="nested_params">
                    <param name="level1.first" value="level1.first replaced" />
                    <param name="level1.first.second" value="level1.first.second replaced" />
                    <param name="level1.first.second.third" value="third replaced" />
                </use-template>
            </response>
        </test>
        <test>
            <request>
                <param name="param3" value="value" />
            </request>
            <response>
                <use-template name="nested_params">
                    <param name="level1.first" value="level1.first replaced" />
                    <param name="level1.first.second" value="level1.first.second replaced" />
                    <param name="level1.first.second[2].fourth" value="fourth replaced" />
                </use-template>
            </response>
        </test>
        <test>
            <request>
                <param name="param4" value="value" />
            </request>
            <response>
                <use-template name="generic_template" />
                <param name="fourth" />
            </response>
        </test>
        <test>
            <request>
                <param name="param5" value="value"/>
            </request>
            <response>
                <param name="list">
                    <use-template name="parent-template"/>
                    <use-template name="child-a"/>
                    <use-template name="child-b"/>
                    <use-template name="parent-template">
                        <param name="object.common_field">
                            <use-template name="common-template">
                                <param name="common-b" value="foo"/>
                            </use-template>
                        </param>
                    </use-template>
                </param>
            </response>
        </test>
        <test>
            <request />
            <response>
                <use-template name="top_template" />
                <param name="old_param" />
            </response>
        </test>
    </category>
</mock-data>

=== valkolovos/mdf/src/test/resources/org/mdf/mockdata/InsertedDataParameterMatcherMorpherTestData.xml
<?xml version="1.0" encoding="UTF-8"?>
<mock-data xmlns="http://www.orbitz.com/schema/mock-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.orbitz.com/schema/mock-data MockTestData.xsd ">
  <parameterMatcher id="insertedDataMatcherMorpher" class="org.mdf.mockdata.InsertedDataParameterMatcherMorpher"/>
  <parameterMorpher ref="insertedDataMatcherMorpher"/>
  <category>
    <test>
      <request>
        <param name="1" value="table TABLE_1 column COLUMN_1"/>
      </request>
      <response>
        <param name="table TABLE_1 column COLUMN_1" value="TABLE_1.COLUMN_1"/>
        <param name="table TABLE_1 column COLUMN_2" value="aliased_name"/>
      </response>
    </test>
    <test>
    	<request>
    		<param name="1" value="inserted into table TABLE_2 column COLUMN_2 value FOO" />
    	</request>
    	<response>
    		<param name="New"/>
    	</response>
    </test>
    <test>
    	<request>
    		<param name="1" value="HOUSE"/>
    	</request>
    	<response>
    		<param name="Resp"/>
    	</response>
    </test>
    
  </category>
</mock-data>

=== valkolovos/mdf/src/test/resources/org/mdf/mockdata/RegExMatcherTestData.xml
<?xml version="1.0" encoding="UTF-8"?>
<mock-data xmlns="http://www.orbitz.com/schema/mock-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.orbitz.com/schema/mock-data ../../../../../main/MockTestData.xsd ">
    <parameterMatcher class="org.mdf.mockdata.RegExMatcher">
        <param name="defaultParameterName" value="path"/>
    </parameterMatcher>
    <category>
        <test>
            <request>
                <param name="path" value="\/doSomething/\w*\/necessaryArgument\/\w*\/anotherNecessaryArgument"/>
            </request>
            <response>
                <param name="works" value="yes"/>
            </response>
        </test>
        <test>
            <request>
                <param name="path" value="\/market\/resolution\/\w+/1/HOT/\w+"/>
            </request>
            <response>
                <param name="works" value="yes"/>
            </response>
        </test>
    </category>
</mock-data>

=== valkolovos/mdf/src/test/resources/org/mdf/mockdata/GenerateMultiplesMorpherTestData.xml
<?xml version="1.0" encoding="UTF-8"?>
<mock-data xmlns="http://www.orbitz.com/schema/mock-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.orbitz.com/schema/mock-data MockTestData.xsd ">
    <parameterMorpher class="org.mdf.mockdata.GenerateMultiplesMorpher"/>
    <category>
        <test>
            <request>
                <param name="testName" value="happyPath" />
            </request>
            <response>
                <param name="multiple" value="4">
                    <param name="data" value="foo" />
                </param>
            </response>
        </test>
        <test>
            <request>
                <param name="testName" value="nullChildParams" />
            </request>
            <response>
                <param name="multiple" />
            </response>
        </test>
        <test>
            <request>
                <param name="testName" value="noNumberParam" />
            </request>
            <response>
                <param name="multiple">
                    <param name="data" value="foo" />
                </param>
            </response>
        </test>
        <test>
            <request>
                <param name="testName" value="noDataParam" />
            </request>
            <response>
                <param name="multiple" value="4" />
            </response>
        </test>
        <test>
            <request>
                <param name="testName" value="dataParamHasSameNameAsMultipleParam" />
            </request>
            <response>
                <param name="multiple" value="4">
                    <!--
                            the "multiple" param will be thrown out because it has no child params
                        -->
                    <param name="multiple" value="2"/>
                    <param name="data" value="foo" />
                </param>
            </response>
        </test>
        <test>
            <request>
                <param name="testName" value="stringForMultiplesParamValue" />
            </request>
            <response>
                <param name="multiple" value="foo">
                    <param name="data" value="foo" />
                </param>
            </response>
        </test>
        <test>
            <request>
                <param name="testName" value="floatForMultiplesParamValue" />
            </request>
            <response>
                <param name="multiple" value="7.2">
                    <param name="data" value="foo" />
                </param>
            </response>
        </test>
    </category>
</mock-data>
